// Copyright 2022 gorse Project Authors
// Copyright 2023 Roman Atachiants
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package asm

import (
	"fmt"
	"os"
	"strings"

	"github.com/kelindar/gocc/internal/config"
	"github.com/klauspost/asmfmt"
)

// Generate generates the Go PLAN9 assembly
func Generate(arch *config.Arch, functions []Function) ([]byte, error) {
	var builder strings.Builder
	builder.WriteString(arch.BuildTags)
	builder.WriteString("// AUTO-GENERATED BY GOCC -- DO NOT EDIT\n")
	for _, function := range functions {
		// Compile global constants
		for _, c := range function.Consts {
			if !c.Inline {
				builder.WriteString(c.Compile(arch))
			}
		}

		builder.WriteString(fmt.Sprintf("\nTEXT ·%v(SB), $0-32\n", function.Name))
		gpIdx, fpIdx := 0, 0
		for i, param := range function.Params {
			instr, err := moveInstruction(arch, param, i*8, &gpIdx, &fpIdx)
			if err != nil {
				return nil, err
			}

			builder.WriteString("\t")
			builder.WriteString(instr)
			builder.WriteString("\n")
		}

		// Validate and compile each line
		for _, line := range function.Lines {
			compiled, err := line.Compile(arch)
			if err != nil {
				return nil, fmt.Errorf("%w in %s; compile with frame pointers omitted", err, function.Name)
			}

			builder.WriteString(compiled)
		}

		// Compile inline constants
		for _, c := range function.Consts {
			if c.Inline {
				builder.WriteString(c.Compile(arch))
			}
		}
	}

	return asmfmt.Format(strings.NewReader(builder.String()))
}

// moveInstruction generates the assembly instruction to move a parameter onto the stack
func moveInstruction(arch *config.Arch, param Param, offset int, gpIdx, fpIdx *int) (string, error) {
	switch {

	// Floating-point parameters
	case !param.IsPointer && (param.Type == "float" || param.Type == "double"):
		if *fpIdx >= len(arch.FloatRegs) {
			return "", fmt.Errorf("gocc: too many floating-point parameters for %s", arch.Name)
		}
		reg := arch.FloatRegs[*fpIdx]
		(*fpIdx)++
		return fmt.Sprintf("%s %s+%d(FP), %s", moveOp(arch, param), param.Name, offset, reg), nil

	// General-purpose parameters
	default:
		if *gpIdx >= len(arch.Registers) {
			return "", fmt.Errorf("gocc: too many general-purpose parameters for %s", arch.Name)
		}
		reg := arch.Registers[*gpIdx]
		(*gpIdx)++
		return fmt.Sprintf("%s %s+%d(FP), %s", moveOp(arch, param), param.Name, offset, reg), nil
	}
}

func moveOp(arch *config.Arch, param Param) string {
	switch {
	case param.IsPointer:
		return arch.CallOp
	case param.Type == "float":
		return arch.Float32Op
	case param.Type == "double":
		return arch.Float64Op
	default:
		return arch.CallOp
	}
}

// GenerateFile generates the Go PLAN9 assembly file
func GenerateFile(arch *config.Arch, path string, functions []Function) error {
	bytes, err := Generate(arch, functions)
	if err != nil {
		return err
	}

	return os.WriteFile(path, bytes, os.ModePerm)
}
