//go:build !noasm && arm64
// AUTO-GENERATED BY GOCC -- DO NOT EDIT

TEXT ·f32_axpy(SB), $0-32
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	MOVD size+16(FP), R2
	MOVD alpha+24(FP), R3
	WORD $0xfd7bbfa9      // stp	x29, x30, [sp, #-16]!
	WORD $0x5f1000f1      // cmp	x2, #4
	WORD $0xfd030091      // mov	x29, sp
	WORD $0x63010054      // b.lo	.LBB0_3
	WORD $0x68008052      // mov	w8, #3
	WORD $0xe90300aa      // mov	x9, x0
	WORD $0xea0301aa      // mov	x10, x1

LBB0_2:
	WORD $0x4101c03d // ldr	q1, [x10]
	WORD $0x08110091 // add	x8, x8, #4
	WORD $0x2205c13c // ldr	q2, [x9], #16
	WORD $0x1f0102eb // cmp	x8, x2
	WORD $0x4110804f // fmla	v1.4s, v2.4s, v0.s[0]
	WORD $0x4105813c // str	q1, [x10], #16
	WORD $0x43ffff54 // b.lo	.LBB0_2

LBB0_3:
	WORD $0x5f0440f2 // tst	x2, #0x3
	WORD $0xe0010054 // b.eq	.LBB0_7
	WORD $0x48f47e92 // and	x8, x2, #0xfffffffffffffffc
	WORD $0x1f0102eb // cmp	x8, x2
	WORD $0x82010054 // b.hs	.LBB0_7
	WORD $0x49f47ed3 // lsl	x9, x2, #2
	WORD $0x480008cb // sub	x8, x2, x8
	WORD $0x2aed7c92 // and	x10, x9, #0xfffffffffffffff0
	WORD $0x29000a8b // add	x9, x1, x10
	WORD $0x0a000a8b // add	x10, x0, x10

LBB0_6:
	WORD $0x414540bc // ldr	s1, [x10], #4
	WORD $0x220140bd // ldr	s2, [x9]
	WORD $0x080500f1 // subs	x8, x8, #1
	WORD $0x2108001f // fmadd	s1, s1, s0, s2
	WORD $0x214500bc // str	s1, [x9], #4
	WORD $0x61ffff54 // b.ne	.LBB0_6

LBB0_7:
	WORD $0xfd7bc1a8 // ldp	x29, x30, [sp], #16
	WORD $0xc0035fd6 // ret

TEXT ·f32_matmul(SB), $0-32
	MOVD dst+0(FP), R0
	MOVD m+8(FP), R1
	MOVD n+16(FP), R2
	MOVD dims+24(FP), R3
	WORD $0xfd7bbfa9     // stp	x29, x30, [sp, #-16]!
	WORD $0x683c40f2     // ands	x8, x3, #0xffff
	WORD $0xfd030091     // mov	x29, sp
	WORD $0xe00c0054     // b.eq	.LBB1_25
	WORD $0x6afc70d3     // lsr	x10, x3, #48
	WORD $0x7f0450f2     // tst	x3, #0x3000000000000
	WORD $0x4b357e92     // and	x11, x10, #0xfffc
	WORD $0x697c50d3     // ubfx	x9, x3, #16, #16
	WORD $0x40114bfa     // ccmp	x10, x11, #0, ne
	WORD $0xec979f1a     // cset	w12, hi
	WORD $0x090c00b4     // cbz	x9, .LBB1_25
	WORD $0x6dfc72d3     // lsr	x13, x3, #50
	WORD $0xad0400b4     // cbz	x13, .LBB1_12
	WORD $0x6c080036     // tbz	w12, #0, .LBB1_19
	WORD $0xec031faa     // mov	x12, xzr
	WORD $0x4df57ed3     // lsl	x13, x10, #2

LBB1_5:
	WORD $0x8f7d099b // mul	x15, x12, x9
	WORD $0xee031faa // mov	x14, xzr
	WORD $0xf00302aa // mov	x16, x2

LBB1_6:
	WORD $0xd1010f8b // add	x17, x14, x15
	WORD $0xf20310aa // mov	x18, x16
	WORD $0x63008052 // mov	w3, #3
	WORD $0x207871bc // ldr	s0, [x1, x17, lsl #2]
	WORD $0xf10300aa // mov	x17, x0

LBB1_7:
	WORD $0x2102c03d // ldr	q1, [x17]
	WORD $0x63100091 // add	x3, x3, #4
	WORD $0x4206c13c // ldr	q2, [x18], #16
	WORD $0x7f000aeb // cmp	x3, x10
	WORD $0x4110804f // fmla	v1.4s, v2.4s, v0.s[0]
	WORD $0x2106813c // str	q1, [x17], #16
	WORD $0x43ffff54 // b.lo	.LBB1_7
	WORD $0xf1030baa // mov	x17, x11

LBB1_9:
	WORD $0x32f67ed3 // lsl	x18, x17, #2
	WORD $0x31060091 // add	x17, x17, #1
	WORD $0x5f0111eb // cmp	x10, x17
	WORD $0x016a72bc // ldr	s1, [x16, x18]
	WORD $0x026872bc // ldr	s2, [x0, x18]
	WORD $0x2108001f // fmadd	s1, s1, s0, s2
	WORD $0x016832bc // str	s1, [x0, x18]
	WORD $0x21ffff54 // b.ne	.LBB1_9
	WORD $0xce050091 // add	x14, x14, #1
	WORD $0x10020d8b // add	x16, x16, x13
	WORD $0xdf0109eb // cmp	x14, x9
	WORD $0x01fdff54 // b.ne	.LBB1_6
	WORD $0x8c050091 // add	x12, x12, #1
	WORD $0x00000d8b // add	x0, x0, x13
	WORD $0x9f0108eb // cmp	x12, x8
	WORD $0x21fcff54 // b.ne	.LBB1_5
	WORD $0x3a000014 // b	.LBB1_25

LBB1_12:
	WORD $0x2c070034 // cbz	w12, .LBB1_25
	WORD $0x6dfc6ed3 // lsr	x13, x3, #46
	WORD $0xec031faa // mov	x12, xzr
	WORD $0xae357c92 // and	x14, x13, #0x3fff0
	WORD $0x4b010bcb // sub	x11, x10, x11
	WORD $0x0d000e8b // add	x13, x0, x14
	WORD $0x4af57ed3 // lsl	x10, x10, #2
	WORD $0x4e000e8b // add	x14, x2, x14

LBB1_14:
	WORD $0x907d099b // mul	x16, x12, x9
	WORD $0xef031faa // mov	x15, xzr
	WORD $0xf1030eaa // mov	x17, x14

LBB1_15:
	WORD $0xf201108b // add	x18, x15, x16
	WORD $0xe0030daa // mov	x0, x13
	WORD $0xe2030baa // mov	x2, x11
	WORD $0x207872bc // ldr	s0, [x1, x18, lsl #2]
	WORD $0xf20311aa // mov	x18, x17

LBB1_16:
	WORD $0x414640bc // ldr	s1, [x18], #4
	WORD $0x020040bd // ldr	s2, [x0]
	WORD $0x420400f1 // subs	x2, x2, #1
	WORD $0x2108001f // fmadd	s1, s1, s0, s2
	WORD $0x014400bc // str	s1, [x0], #4
	WORD $0x61ffff54 // b.ne	.LBB1_16
	WORD $0xef050091 // add	x15, x15, #1
	WORD $0x31020a8b // add	x17, x17, x10
	WORD $0xff0109eb // cmp	x15, x9
	WORD $0x41feff54 // b.ne	.LBB1_15
	WORD $0x8c050091 // add	x12, x12, #1
	WORD $0xad010a8b // add	x13, x13, x10
	WORD $0x9f0108eb // cmp	x12, x8
	WORD $0x61fdff54 // b.ne	.LBB1_14
	WORD $0x1b000014 // b	.LBB1_25

LBB1_19:
	WORD $0xeb031faa // mov	x11, xzr
	WORD $0x4cf57ed3 // lsl	x12, x10, #2

LBB1_20:
	WORD $0x6e7d099b // mul	x14, x11, x9
	WORD $0xed031faa // mov	x13, xzr
	WORD $0xef0302aa // mov	x15, x2

LBB1_21:
	WORD $0xb0010e8b // add	x16, x13, x14
	WORD $0xf1030faa // mov	x17, x15
	WORD $0x72008052 // mov	w18, #3
	WORD $0x3008108b // add	x16, x1, x16, lsl #2
	WORD $0x00ca404d // ld1r	{ v0.4s }, [x16]
	WORD $0xf00300aa // mov	x16, x0

LBB1_22:
	WORD $0x0102c03d // ldr	q1, [x16]
	WORD $0x52120091 // add	x18, x18, #4
	WORD $0x2206c13c // ldr	q2, [x17], #16
	WORD $0x5f020aeb // cmp	x18, x10
	WORD $0x41cc204e // fmla	v1.4s, v2.4s, v0.4s
	WORD $0x0106813c // str	q1, [x16], #16
	WORD $0x43ffff54 // b.lo	.LBB1_22
	WORD $0xad050091 // add	x13, x13, #1
	WORD $0xef010c8b // add	x15, x15, x12
	WORD $0xbf0109eb // cmp	x13, x9
	WORD $0x01feff54 // b.ne	.LBB1_21
	WORD $0x6b050091 // add	x11, x11, #1
	WORD $0x00000c8b // add	x0, x0, x12
	WORD $0x7f0108eb // cmp	x11, x8
	WORD $0x21fdff54 // b.ne	.LBB1_20

LBB1_25:
	WORD $0xfd7bc1a8 // ldp	x29, x30, [sp], #16
	WORD $0xc0035fd6 // ret
