//go:build !noasm && darwin && arm64
// AUTO-GENERATED BY GOCC -- DO NOT EDIT

TEXT ·f32_axpy(SB), $0-32
	MOVD x+0(FP), R0
	MOVD y+8(FP), R1
	MOVD size+16(FP), R2
	MOVD alpha+24(FP), R3
	WORD $0xa9bf7bfd      // stp	x29, x30, [sp, #-16]!
	WORD $0x910003fd      // mov	x29, sp
	WORD $0xf100105f      // cmp	x2, #4
	WORD $0x54000183      // b.lo	LBB0_3
	WORD $0x4e040401      // dup.4s	v1, v0[0]
	WORD $0x52800068      // mov	w8, #3
	WORD $0xaa0003e9      // mov	x9, x0
	WORD $0xaa0103ea      // mov	x10, x1

BB0_2:
	WORD $0x3cc10522 // ldr	q2, [x9], #16
	WORD $0x3dc00143 // ldr	q3, [x10]
	WORD $0x4e21cc43 // fmla.4s	v3, v2, v1
	WORD $0x3c810543 // str	q3, [x10], #16
	WORD $0x91001108 // add	x8, x8, #4
	WORD $0xeb02011f // cmp	x8, x2
	WORD $0x54ffff43 // b.lo	LBB0_2

BB0_3:
	WORD $0xf240045f // tst	x2, #0x3
	WORD $0x540001c0 // b.eq	LBB0_7
	WORD $0x927ef449 // and	x9, x2, #0xfffffffffffffffc
	WORD $0xeb02013f // cmp	x9, x2
	WORD $0x54000162 // b.hs	LBB0_7
	WORD $0xcb090048 // sub	x8, x2, x9
	WORD $0xd37ef52a // lsl	x10, x9, #2
	WORD $0x8b0a0029 // add	x9, x1, x10
	WORD $0x8b0a000a // add	x10, x0, x10

BB0_6:
	WORD $0xbc404541 // ldr	s1, [x10], #4
	WORD $0xbd400122 // ldr	s2, [x9]
	WORD $0x1f000821 // fmadd	s1, s1, s0, s2
	WORD $0xbc004521 // str	s1, [x9], #4
	WORD $0xf1000508 // subs	x8, x8, #1
	WORD $0x54ffff61 // b.ne	LBB0_6

BB0_7:
	WORD $0xa8c17bfd // ldp	x29, x30, [sp], #16
	WORD $0xd65f03c0 // ret

TEXT ·f32_matmul(SB), $0-32
	MOVD dst+0(FP), R0
	MOVD m+8(FP), R1
	MOVD n+16(FP), R2
	MOVD dims+24(FP), R3
	WORD $0xa9be4ff4     // stp	x20, x19, [sp, #-32]!
	WORD $0xa9017bfd     // stp	x29, x30, [sp, #16]
	WORD $0x910043fd     // add	x29, sp, #16
	WORD $0xd370fc68     // lsr	x8, x3, #48
	WORD $0xf250047f     // tst	x3, #0x3000000000000
	WORD $0x1a9f07ee     // cset	w14, ne
	WORD $0x927e3509     // and	x9, x8, #0xfffc
	WORD $0xeb09010a     // subs	x10, x8, x9
	WORD $0x1a9f97ef     // cset	w15, hi
	WORD $0x92403c6b     // and	x11, x3, #0xffff
	WORD $0xb4000aab     // cbz	x11, LBB1_19
	WORD $0xd280000c     // mov	x12, #0
	WORD $0xd3507c6d     // ubfx	x13, x3, #16, #16
	WORD $0xd37ef531     // lsl	x17, x9, #2
	WORD $0x0a0f01ce     // and	w14, w14, w15
	WORD $0x8b11004f     // add	x15, x2, x17
	WORD $0xd37ef510     // lsl	x16, x8, #2
	WORD $0x8b110011     // add	x17, x0, x17
	WORD $0xd372fc63     // lsr	x3, x3, #50
	WORD $0x14000006     // b	LBB1_3

BB1_2:
	WORD $0x9100058c // add	x12, x12, #1
	WORD $0x8b100231 // add	x17, x17, x16
	WORD $0x8b100000 // add	x0, x0, x16
	WORD $0xeb0b019f // cmp	x12, x11
	WORD $0x540008e0 // b.eq	LBB1_19

BB1_3:
	WORD $0xb4ffff6d // cbz	x13, LBB1_2
	WORD $0x9b0d7d84 // mul	x4, x12, x13
	WORD $0xb4000623 // cbz	x3, LBB1_14
	WORD $0xd2800005 // mov	x5, #0
	WORD $0xaa0203e6 // mov	x6, x2
	WORD $0x3600038e // tbz	w14, #0, LBB1_11

BB1_6:
	WORD $0xd2800007 // mov	x7, #0
	WORD $0x8b0400b3 // add	x19, x5, x4
	WORD $0xbc737820 // ldr	s0, [x1, x19, lsl #2]
	WORD $0x4e040401 // dup.4s	v1, v0[0]
	WORD $0x52800073 // mov	w19, #3

BB1_7:
	WORD $0x3ce76802 // ldr	q2, [x0, x7]
	WORD $0x3ce768c3 // ldr	q3, [x6, x7]
	WORD $0x4e21cc62 // fmla.4s	v2, v3, v1
	WORD $0x3ca76802 // str	q2, [x0, x7]
	WORD $0x91001273 // add	x19, x19, #4
	WORD $0x910040e7 // add	x7, x7, #16
	WORD $0xeb08027f // cmp	x19, x8
	WORD $0x54ffff23 // b.lo	LBB1_7
	WORD $0xaa0903e7 // mov	x7, x9

BB1_9:
	WORD $0xd37ef4f3 // lsl	x19, x7, #2
	WORD $0xbc7368c1 // ldr	s1, [x6, x19]
	WORD $0xbc736802 // ldr	s2, [x0, x19]
	WORD $0x1f000821 // fmadd	s1, s1, s0, s2
	WORD $0xbc336801 // str	s1, [x0, x19]
	WORD $0x910004e7 // add	x7, x7, #1
	WORD $0xeb07011f // cmp	x8, x7
	WORD $0x54ffff21 // b.ne	LBB1_9
	WORD $0x910004a5 // add	x5, x5, #1
	WORD $0x8b1000c6 // add	x6, x6, x16
	WORD $0xeb0d00bf // cmp	x5, x13
	WORD $0x54fffce1 // b.ne	LBB1_6
	WORD $0x17ffffdb // b	LBB1_2

BB1_11:
	WORD $0x8b0400a7 // add	x7, x5, x4
	WORD $0x8b070827 // add	x7, x1, x7, lsl #2
	WORD $0x4d40c8e0 // ld1r.4s	{ v0 }, [x7]
	WORD $0xaa0003e7 // mov	x7, x0
	WORD $0x52800073 // mov	w19, #3
	WORD $0xaa0603f4 // mov	x20, x6

BB1_12:
	WORD $0x3cc10681 // ldr	q1, [x20], #16
	WORD $0x3dc000e2 // ldr	q2, [x7]
	WORD $0x4e20cc22 // fmla.4s	v2, v1, v0
	WORD $0x3c8104e2 // str	q2, [x7], #16
	WORD $0x91001273 // add	x19, x19, #4
	WORD $0xeb08027f // cmp	x19, x8
	WORD $0x54ffff43 // b.lo	LBB1_12
	WORD $0x910004a5 // add	x5, x5, #1
	WORD $0x8b1000c6 // add	x6, x6, x16
	WORD $0xeb0d00bf // cmp	x5, x13
	WORD $0x54fffe01 // b.ne	LBB1_11
	WORD $0x17ffffc9 // b	LBB1_2

BB1_14:
	WORD $0x34fff90e // cbz	w14, LBB1_2
	WORD $0xd2800005 // mov	x5, #0
	WORD $0xaa0f03e6 // mov	x6, x15

BB1_16:
	WORD $0x8b0400a7 // add	x7, x5, x4
	WORD $0xbc677820 // ldr	s0, [x1, x7, lsl #2]
	WORD $0xaa1103e7 // mov	x7, x17
	WORD $0xaa0a03f3 // mov	x19, x10
	WORD $0xaa0603f4 // mov	x20, x6

BB1_17:
	WORD $0xbc404681 // ldr	s1, [x20], #4
	WORD $0xbd4000e2 // ldr	s2, [x7]
	WORD $0x1f000821 // fmadd	s1, s1, s0, s2
	WORD $0xbc0044e1 // str	s1, [x7], #4
	WORD $0xf1000673 // subs	x19, x19, #1
	WORD $0x54ffff61 // b.ne	LBB1_17
	WORD $0x910004a5 // add	x5, x5, #1
	WORD $0x8b1000c6 // add	x6, x6, x16
	WORD $0xeb0d00bf // cmp	x5, x13
	WORD $0x54fffe41 // b.ne	LBB1_16
	WORD $0x17ffffb6 // b	LBB1_2

BB1_19:
	WORD $0xa9417bfd // ldp	x29, x30, [sp, #16]
	WORD $0xa8c24ff4 // ldp	x20, x19, [sp], #32
	WORD $0xd65f03c0 // ret
