//go:build !noasm && amd64
// AUTO-GENERATED BY GOCC -- DO NOT EDIT

package simd

import "unsafe"

//go:noescape,nosplit
func f32_axpy(x unsafe.Pointer, y unsafe.Pointer, size uint64, alpha float32)

//go:noescape,nosplit
func f32_matmul(dst unsafe.Pointer, m unsafe.Pointer, n unsafe.Pointer, dims uint64)
