//go:build !noasm && amd64
// AUTO-GENERATED BY GOCC -- DO NOT EDIT

package simd

import "unsafe"

//go:noescape,nosplit
func uint8_avx2_mul(input1 unsafe.Pointer, input2 unsafe.Pointer, output unsafe.Pointer, size uint64)
